"""create core domain tables

Revision ID: 3750513bd3c4
Revises:
Create Date: 2026-08-03 15:56:10.864189

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3750513bd3c4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farmers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=False),
        sa.Column(
            "preferred_language",
            sa.Enum("uz", "ru", "en", name="preferredlanguage", native_enum=False, length=8),
            server_default="uz",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_farmers_phone"), "farmers", ["phone"], unique=True)
    op.create_table(
        "fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farmer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("geojson_polygon", sa.JSON(), nullable=False),
        sa.Column("area_hectares", sa.Float(), nullable=False),
        sa.Column("centroid_latitude", sa.Float(), nullable=False),
        sa.Column("centroid_longitude", sa.Float(), nullable=False),
        sa.Column(
            "crop_type",
            sa.Enum(
                "cotton",
                "wheat",
                "orchard",
                "vineyard",
                "vegetables",
                name="croptype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("crop_variety", sa.String(length=100), nullable=True),
        sa.Column("planting_date", sa.Date(), nullable=False),
        sa.Column("expected_harvest_date", sa.Date(), nullable=True),
        sa.Column(
            "crop_stage_override",
            sa.Enum(
                "initial",
                "development",
                "mid",
                "late",
                name="cropstage",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "irrigation_method",
            sa.Enum(
                "drip",
                "sprinkler",
                "furrow",
                "basin",
                "unknown",
                name="irrigationmethod",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "soil_texture",
            sa.Enum(
                "sand",
                "sandy_loam",
                "loam",
                "clay_loam",
                "clay",
                "unknown",
                name="soiltexture",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("root_depth_override", sa.Float(), nullable=True),
        sa.Column("field_capacity_override", sa.Float(), nullable=True),
        sa.Column("wilting_point_override", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("area_hectares > 0", name="ck_fields_area_positive"),
        sa.CheckConstraint(
            "centroid_latitude BETWEEN -90 AND 90", name="ck_fields_centroid_lat_range"
        ),
        sa.CheckConstraint(
            "centroid_longitude BETWEEN -180 AND 180", name="ck_fields_centroid_lon_range"
        ),
        sa.CheckConstraint(
            "expected_harvest_date IS NULL OR expected_harvest_date > planting_date",
            name="ck_fields_harvest_after_planting",
        ),
        sa.CheckConstraint(
            "field_capacity_override IS NULL"
            " OR (field_capacity_override > 0 AND field_capacity_override < 1)",
            name="ck_fields_field_capacity_range",
        ),
        sa.CheckConstraint(
            "root_depth_override IS NULL OR root_depth_override > 0",
            name="ck_fields_root_depth_positive",
        ),
        sa.CheckConstraint(
            "wilting_point_override IS NULL"
            " OR (wilting_point_override > 0 AND wilting_point_override < 1)",
            name="ck_fields_wilting_point_range",
        ),
        sa.ForeignKeyConstraint(["farmer_id"], ["farmers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fields_farmer_id"), "fields", ["farmer_id"], unique=False)
    op.create_index(
        "ix_fields_farmer_id_created_at", "fields", ["farmer_id", "created_at"], unique=False
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("analysis_date", sa.Date(), nullable=False),
        sa.Column(
            "data_mode",
            sa.Enum("fixture", "live", name="analysisdatamode", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("satellite_summary", sa.JSON(), nullable=True),
        sa.Column("weather_summary", sa.JSON(), nullable=True),
        sa.Column("water_balance_summary", sa.JSON(), nullable=True),
        sa.Column("recommendation", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.JSON(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column("calculation_version", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analyses_field_id"), "analyses", ["field_id"], unique=False)
    op.create_table(
        "irrigation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("amount_mm", sa.Float(), nullable=True),
        sa.Column("total_volume_m3", sa.Float(), nullable=True),
        sa.Column("flow_rate_m3_hour", sa.Float(), nullable=True),
        sa.Column(
            "qualitative_amount",
            sa.Enum(
                "little",
                "moderate",
                "a_lot",
                name="qualitativeamount",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "value_source",
            sa.Enum(
                "measured", "farmer_estimate", name="valuesource", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_mm IS NULL OR amount_mm >= 0", name="ck_irrigation_amount_mm_non_negative"
        ),
        sa.CheckConstraint(
            "duration_minutes IS NULL OR duration_minutes > 0",
            name="ck_irrigation_duration_positive",
        ),
        sa.CheckConstraint(
            "flow_rate_m3_hour IS NULL OR flow_rate_m3_hour >= 0",
            name="ck_irrigation_flow_rate_non_negative",
        ),
        sa.CheckConstraint(
            "total_volume_m3 IS NULL OR total_volume_m3 >= 0",
            name="ck_irrigation_total_volume_non_negative",
        ),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_irrigation_events_field_id"), "irrigation_events", ["field_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_irrigation_events_field_id"), table_name="irrigation_events")
    op.drop_table("irrigation_events")
    op.drop_index(op.f("ix_analyses_field_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index("ix_fields_farmer_id_created_at", table_name="fields")
    op.drop_index(op.f("ix_fields_farmer_id"), table_name="fields")
    op.drop_table("fields")
    op.drop_index(op.f("ix_farmers_phone"), table_name="farmers")
    op.drop_table("farmers")
    # ### end Alembic commands ###
